In [3]:
import pandas as pd
import numpy as np

In [4]:
billioner=pd.read_csv("Forbes Billionaires.csv")

In [5]:
billioner

,Rank,Name,Networth,Age,Country,Source,Industry
0,1,Elon Musk,219.0,50,United States,"Tesla, SpaceX",Automotive
1,2,Jeff Bezos,171.0,58,United States,Amazon,Technology
2,3,Bernard Arnault & family,158.0,73,France,LVMH,Fashion & Retail
3,4,Bill Gates,129.0,66,United States,Microsoft,Technology
4,5,Warren Buffett,118.0,91,United States,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...,...
2595,2578,Jorge Gallardo Ballart,1.0,80,Spain,pharmaceuticals,Healthcare
2596,2578,Nari Genomal,1.0,82,Philippines,apparel,Fashion & Retail
2597,2578,Ramesh Genomal,1.0,71,Philippines,apparel,Fashion & Retail
2598,2578,Sunder Genomal,1.0,68,Philippines,garments,Fashion & Retail
2599,2578,Horst-Otto Gerberding,1.0,69,Germany,flavors and fragrances,Food & Beverage

In [11]:
billioner.head(10) #It reads First 10 bit (n is changable)

,Rank,Name,Networth,Age,Country,Source,Industry
0,1,Elon Musk,219.0,50,United States,"Tesla, SpaceX",Automotive
1,2,Jeff Bezos,171.0,58,United States,Amazon,Technology
2,3,Bernard Arnault & family,158.0,73,France,LVMH,Fashion & Retail
3,4,Bill Gates,129.0,66,United States,Microsoft,Technology
4,5,Warren Buffett,118.0,91,United States,Berkshire Hathaway,Finance & Investments
5,6,Larry Page,111.0,49,United States,Google,Technology
6,7,Sergey Brin,107.0,48,United States,Google,Technology
7,8,Larry Ellison,106.0,77,United States,software,Technology
8,9,Steve Ballmer,91.4,66,United States,Microsoft,Technology
9,10,Mukesh Ambani,90.7,64,India,diversified,diversified

In [22]:
len(billioner.index) #I can learn how many indexes are there in this dataset

2600

In [23]:
billioner["Networth"].mean() #First İt rows Networth value if ı add .mean,I take the average

4.860750000000006

In [24]:
billioner["Networth"].max()#Same as mean but this time I learned max Networth or value

219.0

In [25]:
billioner["Networth"].max()

219.0

In [37]:
billioner[billioner["Networth"]==billioner["Networth"].max()]["Name"].iloc[0] #I found the man with the highest Networth

'Elon Musk '

In [41]:
billioner[billioner["Name"]=="Bernard Arnault & family"]["Country"] #Normalde İsmi Bernard arnault a eşit olanı çağırması gerekiyordu neden cağırmadı anlamadım

Series([], Name: Country, dtype: object)

In [42]:
billioner.groupby("Industry").mean() #I found the average of everything by industry

                                   Rank   Networth        Age
Industry
Automotive                   1168.623188  8.443478  63.449275
Construction & Engineering   1518.558140  2.811628  65.116279
Energy                       1177.204301  4.250538  67.107527
Fashion & Retail             1210.711382  6.557724  67.325203
Finance & Investments        1225.562176  4.493005  64.536269
Food & Beverage              1193.213930  4.643532  65.800995
Gambling & Casinos           1076.304348  4.678261  67.608696
Healthcare                   1423.353774  3.343868  63.976415
Logistics                    1186.228571  5.605714  67.628571
Manufacturing                1383.208075  3.353416  63.583851
Media & Entertainment        1255.200000  5.195789  63.063158
Metals & Mining              1149.402985  5.816418  60.029851
Real Estate                  1297.518519  3.628571  67.550265
Service                      1286.058824  3.649020  68.058824
Sports                       1119.038462  3.753846  71.076923
Technology                   1231.310030  6.590881  56.276596
Telecom                      1341.200000  5.860000  64.514286
diversified                  1309.573034  5.278090  68.303371

In [44]:
billioner["Industry"].nunique() #I found how many diffirent Industry are there in this dataset

18

In [45]:
billioner["Industry"].value_counts() #Her endistüride kaç farklı kişi var

Finance & Investments          386
Technology                     329
Manufacturing                  322
Fashion & Retail               246
Healthcare                     212
Food & Beverage                201
Real Estate                    189
diversified                    178
Media & Entertainment           95
Energy                          93
Automotive                      69
Metals & Mining                 67
Service                         51
Construction & Engineering      43
Logistics                       35
Telecom                         35
Sports                          26
Gambling & Casinos              23
Name: Industry, dtype: int64

In [48]:
def mal_find(last_Name):
    if "mal" in last_Name.lower():   #Soyadlarında 'MAL' gecen indexleri buldum
        return True
    return False
billioner[billioner["Name"].apply(mal_find)]

,Rank,Name,Networth,Age,Country,Source,Industry
320,321,John Malone,7.4,81,United States,cable television,Media & Entertainment
701,687,Ajay Piramal,4.2,66,India,pharmaceuticals,Healthcare
865,851,Mary Alice Dorrance Malone,3.5,72,United States,Campbell Soup,Food & Beverage
1219,1196,Nirmal Minda,2.6,64,India,auto parts,Automotive
1692,1645,Bill Malhotra,1.8,72,Canada,real estate,Real Estate
2018,1929,Rafique Malik,1.5,71,India,footwear,Fashion & Retail
2596,2578,Nari Genomal,1.0,82,Philippines,apparel,Fashion & Retail
2597,2578,Ramesh Genomal,1.0,71,Philippines,apparel,Fashion & Retail
2598,2578,Sunder Genomal,1.0,68,Philippines,garments,Fashion & Retail

In [49]:
print(billioner.tail()) #for viewing the last rows of the DataFrame.

      Rank                      Name  Networth  Age      Country  \
2595   2578  Jorge Gallardo Ballart        1.0   80        Spain
2596   2578            Nari Genomal        1.0   82  Philippines
2597   2578          Ramesh Genomal        1.0   71  Philippines
2598   2578          Sunder Genomal        1.0   68  Philippines
2599   2578   Horst-Otto Gerberding        1.0   69      Germany

                      Source           Industry
2595         pharmaceuticals        Healthcare
2596                 apparel  Fashion & Retail
2597                 apparel  Fashion & Retail
2598                garments  Fashion & Retail
2599  flavors and fragrances   Food & Beverage

In [53]:
billioner.isnull().sum()

Rank        0
Name        0
Networth    0
Age         0
Country     0
Source      0
Industry    0
dtype: int64